# Generated by Django 2.1.5 on 2019-06-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(choices=[('CSE', 'Computer Science And Engineering'), ('MnC', 'Mathematics And Computing'), ('ECE', 'Electronics And Communication Enginnering'), ('EEE', 'Electrical And Electronics Engineering')], default='None', max_length=3, unique=True),
        ),
    ]
